"""
Integration module.

Converts a discovered strategy into a Python module compatible with the
existing trading engine (app.core.strategy.*).

The generated module exposes a class ``DiscoveredStrategy`` that follows
the same interface patterns as ``MultiTimeframeAnalyzer``:
  - ``analyze(symbol, df) -> dict``  with keys like direction, entry_price,
    stop_loss, take_profit, tradeable.
"""
from __future__ import annotations

import os
import textwrap
from typing import Optional

from app.discovery.ranking import RankedStrategy
from app.discovery.strategy_config import Condition


def _cond_to_code(cond: Condition, df_var: str = "df") -> str:
    """Convert a Condition to a Python expression string."""

    def _operand(op, use_iloc: bool = True):
        if isinstance(op, str):
            base = f'{df_var}["{op}"]'
            return f"{base}.iloc[-1]" if use_iloc else base
        if isinstance(op, (int, float)):
            return repr(op)
        return repr(op)

    if cond.op in (">", "<", ">=", "<=", "=="):
        left = _operand(cond.left)
        right = _operand(cond.right)
        return f"({left} {cond.op} {right})"
    if cond.op == "cross_above":
        left = _operand(cond.left, use_iloc=False)
        right = _operand(cond.right, use_iloc=False)
        return f"(({left}.iloc[-1] > {right}.iloc[-1]) and ({left}.iloc[-2] <= {right}.iloc[-2]))"
    if cond.op == "cross_below":
        left = _operand(cond.left, use_iloc=False)
        right = _operand(cond.right, use_iloc=False)
        return f"(({left}.iloc[-1] < {right}.iloc[-1]) and ({left}.iloc[-2] >= {right}.iloc[-2]))"
    return "True"


def _cond_list_to_code(conditions: list[Condition], df_var: str = "df") -> str:
    if not conditions:
        return "False"
    parts = [_cond_to_code(c, df_var) for c in conditions]
    return " and ".join(parts)


def generate_strategy_module(
    ranked_strategy: RankedStrategy,
    output_dir: str = "app/core/strategy",
) -> str:
    """
    Generate a Python module for the top-ranked discovered strategy.

    Returns the path of the generated file.
    """
    strat = ranked_strategy.strategy
    safe_name = strat.name.replace("-", "_")
    filename = f"discovered_{safe_name}.py"
    filepath = os.path.join(output_dir, filename)

    long_entry_code = _cond_list_to_code(strat.long_entry)
    short_entry_code = _cond_list_to_code(strat.short_entry)
    long_exit_code = _cond_list_to_code(strat.long_exit) if strat.long_exit else "False"
    short_exit_code = _cond_list_to_code(strat.short_exit) if strat.short_exit else "False"

    params_repr = repr(strat.params)
    perf_summary = ""
    if ranked_strategy.oos_report:
        r = ranked_strategy.oos_report
        perf_summary = (
            f"OOS: Sharpe={r.sharpe_ratio:.2f}, PF={r.profit_factor:.2f}, "
            f"DD={r.max_drawdown:.2%}, WR={r.win_rate:.1%}, "
            f"Trades={r.total_trades}"
        )

    module_code = textwrap.dedent(f'''\
        """
        Auto-discovered strategy: {strat.name}
        Family: {strat.family}
        Description: {strat.description}
        Composite score: {ranked_strategy.composite_score:.4f}
        Performance: {perf_summary}

        Generated by the Strategy Discovery Engine.
        """
        from __future__ import annotations

        from dataclasses import dataclass
        from typing import Optional

        import pandas as pd
        import numpy as np

        from app.discovery.indicators import add_all_discovery_indicators
        from app.discovery.backtest import _add_derived_columns
        from app.utils.indicators import calculate_atr


        STRATEGY_NAME = "{strat.name}"
        STRATEGY_FAMILY = "{strat.family}"
        STRATEGY_PARAMS = {params_repr}


        @dataclass
        class DiscoveredSignal:
            tradeable: bool = False
            direction: Optional[str] = None
            entry_price: float = 0.0
            stop_loss: float = 0.0
            take_profit: float = 0.0
            strategy_name: str = STRATEGY_NAME
            confidence: float = 0.0


        class DiscoveredStrategy:
            """
            {strat.description}

            SL: {strat.sl_atr_mult:.1f} × ATR
            TP: {strat.tp_rr:.1f} R:R
            Risk: {strat.risk_pct:.2%} per trade
            """

            def __init__(self):
                self.name = STRATEGY_NAME
                self.family = STRATEGY_FAMILY
                self.params = STRATEGY_PARAMS
                self.sl_atr_mult = {strat.sl_atr_mult}
                self.tp_rr = {strat.tp_rr}
                self.risk_pct = {strat.risk_pct}

            def analyze(self, symbol: str, df: pd.DataFrame) -> DiscoveredSignal:
                """
                Analyse OHLCV DataFrame and return a trade signal.

                Args:
                    symbol: Trading symbol (e.g. "EURUSD").
                    df: OHLCV DataFrame with columns open, high, low, close, volume.
                        Must contain enough bars for indicator warm-up (~200).

                Returns:
                    DiscoveredSignal with trade details if conditions are met.
                """
                if len(df) < 210:
                    return DiscoveredSignal()

                df = add_all_discovery_indicators(df)
                df = _add_derived_columns(df)

                signal = DiscoveredSignal()

                try:
                    long_entry = {long_entry_code}
                    short_entry = {short_entry_code}
                except Exception:
                    return signal

                if not long_entry and not short_entry:
                    return signal

                close = df["close"].iloc[-1]
                atr = df["atr_14"].iloc[-1] if "atr_14" in df.columns else close * 0.001

                if long_entry:
                    signal.tradeable = True
                    signal.direction = "long"
                    signal.entry_price = close
                    signal.stop_loss = close - atr * self.sl_atr_mult
                    signal.take_profit = close + atr * self.sl_atr_mult * self.tp_rr
                    signal.confidence = 0.7
                elif short_entry:
                    signal.tradeable = True
                    signal.direction = "short"
                    signal.entry_price = close
                    signal.stop_loss = close + atr * self.sl_atr_mult
                    signal.take_profit = close - atr * self.sl_atr_mult * self.tp_rr
                    signal.confidence = 0.7

                return signal

            def should_exit(self, direction: str, df: pd.DataFrame) -> bool:
                """Check indicator-based exit conditions."""
                if len(df) < 210:
                    return False
                try:
                    df = add_all_discovery_indicators(df)
                    df = _add_derived_columns(df)
                    if direction == "long":
                        return bool({long_exit_code})
                    else:
                        return bool({short_exit_code})
                except Exception:
                    return False
    ''')

    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, "w") as f:
        f.write(module_code)

    return filepath
