"""
Auto-discovered strategy: trend_sma_e2a6b3
Family: trend_following
Description: SMA 50/200 +MACD
Composite score: 0.9433
Performance: OOS: Sharpe=10.30, PF=3.56, DD=2.15%, WR=66.7%, Trades=9

Generated by the Strategy Discovery Engine.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

import pandas as pd
import numpy as np

from app.discovery.indicators import add_all_discovery_indicators
from app.discovery.backtest import _add_derived_columns
from app.utils.indicators import calculate_atr


STRATEGY_NAME = "trend_sma_e2a6b3"
STRATEGY_FAMILY = "trend_following"
STRATEGY_PARAMS = {'fast': 50, 'slow': 200, 'macd_filter': True, 'sl': 1.5, 'tp': 2.0}


@dataclass
class DiscoveredSignal:
    tradeable: bool = False
    direction: Optional[str] = None
    entry_price: float = 0.0
    stop_loss: float = 0.0
    take_profit: float = 0.0
    strategy_name: str = STRATEGY_NAME
    confidence: float = 0.0


class DiscoveredStrategy:
    """
    SMA 50/200 +MACD

    SL: 1.5 × ATR
    TP: 2.0 R:R
    Risk: 1.00% per trade
    """

    def __init__(self):
        self.name = STRATEGY_NAME
        self.family = STRATEGY_FAMILY
        self.params = STRATEGY_PARAMS
        self.sl_atr_mult = 1.5
        self.tp_rr = 2.0
        self.risk_pct = 0.01

    def analyze(self, symbol: str, df: pd.DataFrame) -> DiscoveredSignal:
        """
        Analyse OHLCV DataFrame and return a trade signal.

        Args:
            symbol: Trading symbol (e.g. "EURUSD").
            df: OHLCV DataFrame with columns open, high, low, close, volume.
                Must contain enough bars for indicator warm-up (~200).

        Returns:
            DiscoveredSignal with trade details if conditions are met.
        """
        if len(df) < 210:
            return DiscoveredSignal()

        df = add_all_discovery_indicators(df)
        df = _add_derived_columns(df)

        signal = DiscoveredSignal()

        try:
            long_entry = ((df["sma_50"].iloc[-1] > df["sma_200"].iloc[-1]) and (df["sma_50"].iloc[-2] <= df["sma_200"].iloc[-2])) and (df["macd_hist_12_26_9"].iloc[-1] > 0)
            short_entry = ((df["sma_50"].iloc[-1] < df["sma_200"].iloc[-1]) and (df["sma_50"].iloc[-2] >= df["sma_200"].iloc[-2])) and (df["macd_hist_12_26_9"].iloc[-1] < 0)
        except Exception:
            return signal

        if not long_entry and not short_entry:
            return signal

        close = df["close"].iloc[-1]
        atr = df["atr_14"].iloc[-1] if "atr_14" in df.columns else close * 0.001

        if long_entry:
            signal.tradeable = True
            signal.direction = "long"
            signal.entry_price = close
            signal.stop_loss = close - atr * self.sl_atr_mult
            signal.take_profit = close + atr * self.sl_atr_mult * self.tp_rr
            signal.confidence = 0.7
        elif short_entry:
            signal.tradeable = True
            signal.direction = "short"
            signal.entry_price = close
            signal.stop_loss = close + atr * self.sl_atr_mult
            signal.take_profit = close - atr * self.sl_atr_mult * self.tp_rr
            signal.confidence = 0.7

        return signal

    def should_exit(self, direction: str, df: pd.DataFrame) -> bool:
        """Check indicator-based exit conditions."""
        if len(df) < 210:
            return False
        try:
            df = add_all_discovery_indicators(df)
            df = _add_derived_columns(df)
            if direction == "long":
                return bool(((df["sma_50"].iloc[-1] < df["sma_200"].iloc[-1]) and (df["sma_50"].iloc[-2] >= df["sma_200"].iloc[-2])))
            else:
                return bool(((df["sma_50"].iloc[-1] > df["sma_200"].iloc[-1]) and (df["sma_50"].iloc[-2] <= df["sma_200"].iloc[-2])))
        except Exception:
            return False
